### ISSUE TITLE
Now gg fix is being applied not ending

### ISSUE THREAD

**Issue by dude363635** [zgr2575/SlowGuardian#4]
**Describe the bug**
I have hosted it on AWS and managed to get it working

**To Reproduce**
1. Go to http://3.104.123.1:8080/
2. Enter a URL
3. Voila

**Expected behavior**
The site should just start loading.

**Desktop (please complete the following information):**

- OS: Chrome OS
- Browser Chrome
- Version 126

**Additional context**
Remember me from the other issue? :D

**Comment by zgr2575** [comment]
Hello dude! 

Glad to hear from you again, and yes I remember you! 
Let me attempt to diagnose this issue, and try to recreate this, 

SlowGuardian is not actively maintained outside of the school season; it's mainly just me releasing a big update and using this time to perfect and work on it! 


Cya after I figure this out!

**Comment by zgr2575** [comment]
I could not access your link. Are your AWS settings set to public?

**Comment by zgr2575** [comment]
its returning: bad gateway which is not an error this version of SmarterBackend can output.

**Comment by dude363635** [comment]
Hey zgr,
Thanks for replying! Really appreciate it when people reply quickly :) Yeah so I tried to host Utopia on the VPS after (a bad idea in hindsight) then it kinda went spastic and wouldn't remove again so I shut the VPS down and made another one. I will set it up again and show you the error. I was using the free tier of AWS VPS (1vCPU, 1GB RAM, 20GB SSD), if you would like to try this yourself.
Kind regards,
dude365635

**Comment by zgr2575** [comment]
Hey dude, 

I am sorry to hear about these troubles! Also while sbe is very light weight that might not be enough computing power to run the proxy, I will get back to you shortly with a solution.

**Comment by zgr2575** [comment]
Also the error will do wonders, because I haven't updated my UV client since 2023. I think it's time I do a recode.

**Comment by dude363635** [comment]
Hey again zgr,
SOrry i haven't been in context for the past 2 days, I was on a camp. Yeah I thought maybe that had something to do with it... I now have a VPS with 2vCPUs and 4GB RAM, do you think that will be enough? Also, can't wait for the recode! Gonna be awesome!

**Comment by zgr2575** [comment]
Hey dude,
That will be MORE than enough! And welcome back from camp! I plan on starting tomorrow because today is my birthday!

If you need further assistance let me know!

**Comment by dude363635** [comment]
Hello zgr,
Ok, thats good! I'll have to remember how I configured the ports because I cant seem to allow the right ports to do the right things but ill figure it out. Also, happy birthday! Hope you are having a great day!

**Comment by zgr2575** [comment]
Hey Dude!

Thanks! Also there are plenty of youtube tutorials to help you with port forwarding. 
If you want I could like one

**Comment by zgr2575** [comment]
Hey dude!

I am excited to inform you I have started working on V8! 

I hope I can get it in the testing branch soon!!

**Comment by dude363635** [comment]
Hey zgr,
Yeah i've done it before ill just refer back to my earlier example VPS and ill just copy the config. Can't wait for V9!!

**Comment by zgr2575** [comment]
Hey dude!

Alrighty, well if you need anything let me know!

**Comment by dude363635** [comment]
Hey zgr,
I'm just gonna try it on the VPS again real quick, I haven't been able to as my previous hacks haven't been working so It has taken me a while to try this stuff again.

**Comment by zgr2575** [comment]
Sorry for this really really late reply,
I have deployed SG on my website:
https://sg.zadmin.xyz

So you can probably use that.

**Comment by dude363635** [comment]
Oh cool! Sorry for the (also) late reply...
Is development going to continue? I can see from the main branch the last development was 5 months ago....?

**Comment by zgr2575** [comment]
Its all good, and I am going to continue to try to develop new features, but it is getting harder. I barely have the time to anymore. I will be able to push bug fixes, etc. But idk if there will be major shifts in development soon.

**Comment by dude363635** [comment]
OK, fair enough! I think all that is really needed is either (a) the option to disable the Now.gg fix, or (b) make the fix faster or something. It would be really useful as I don't actually use Now.gg (some friends do though, so it might be useful). 
Thanks for being here!
dude365635
